!!CHANGE BASE, merge after PMA-029!! PMA-030(AuthForm refactor)
AlexanderSUS/project-management-app pull request #26
Opened 2022-05-21 07:27 UTC by AlexanderSUS

1. Create one reusable form for user authorization
2. Rename BoardForm to ModalForm and move in direct in src folder

2022-05-22 11:04 UTC, allyksander approved these changes

2022-05-22 11:06 UTC, allyksander commented
*Note:
There is two warnings in Login.tsx(26 line in useEffect) and in Registration.tsx (37 line in useEffect)
https://prnt.sc/M_lQxlX3NFPi

2022-05-23 03:43 UTC, Gibr requested changes

2022-05-23 03:43 UTC, Gibr commented on src/components/AuthForm.tsx
> +              label={input.label}
Change to 
label={t(input.label)}

2022-05-23 20:48 UTC, AlexanderSUS commented on src/components/AuthForm.tsx
> +              label={input.label}
Done

2022-05-23 21:06 UTC, merged