PMA-003(MUI) + PMA-019(app-design)
AlexanderSUS/project-management-app pull request #5
Opened 2022-05-08 20:51 UTC by allyksander

1. Add sass
2. Add mui
3. Create muiTheme ('./app/constants/muiTheme') with main defaults set of colors and breakpoints
4. Replaced some components with muiComponents (for demonstration)

*Note:
- I create thie branch from PMA-009 (I used these components for replacing with mui components) -> merging after PMA-009
- There is some problem with Link from 'react-router-dom' - I not find good solution, how to combine this with muiComponents. My be use regular style for this? (We can take colors from const muiTheme for it).

2022-05-08 23:57 UTC, AlexanderSUS commented on src/components/Header/Header.tsx
> +          }}
To avoid inline styles better use 'styled components', you should style this Grid component and move  it  in separate file to folder with Header.tsx https://mui.com/material-ui/guides/interoperability/#styled-components.

2022-05-09 00:02 UTC, AlexanderSUS commented on package.json
> +    "sass": "^1.51.0",
Actually you don't need sass, because in case of custom styles 'styled components' using sass under hood

2022-05-09 00:03 UTC, AlexanderSUS requested changes
Move components with inline styles in separate files

2022-05-09 12:39 UTC, AlexanderSUS approved these changes

2022-05-09 19:30 UTC, allyksander commented on src/components/Header/Header.tsx
> +          }}
Done

2022-05-09 19:30 UTC, allyksander commented on package.json
> +    "sass": "^1.51.0",
Done

2022-05-10 15:38 UTC, AlexanderSUS commented on src/components/LinkStyled/LinkStyled.tsx
> +export default function LinkStyled(props: LinkProps & React.RefAttributes<HTMLAnchorElement>) {
The same as above

2022-05-10 15:40 UTC, AlexanderSUS commented on src/components/FormField/FormField.tsx
> +export default function FormField(props: TextFieldProps) {
If I don't mistake, you not obligated export as you do with FormField, will be enough export only CustomizedTextField and use it as is.

2022-05-10 15:44 UTC, AlexanderSUS reviewed
Leave two comments, please, fix it

2022-05-10 23:55 UTC, merged